#### Numpy

- Pandas : https://pandas.pydata.org/
- Numpy : https://numpy.org/

- 수치해석, 수학적 처리를 위한 라이브러리(모듈) - Scipy, Pandas, Matploplib


##### Numpy 설치
```python
! pip install numpy
```

In [1]:
# 현재 버전 확인
!pip list

Package           Version
----------------- -------
asttokens         2.2.1
backcall          0.2.0
colorama          0.4.6
comm              0.1.3
contourpy         1.1.0
cycler            0.11.0
debugpy           1.6.7
decorator         5.1.1
et-xmlfile        1.1.0
executing         1.2.0
Faker             18.11.1
fonttools         4.40.0
ipykernel         6.23.2
ipython           8.14.0
jedi              0.18.2
Jinja2            3.1.2
jupyter_client    8.2.0
jupyter_core      5.3.1
kiwisolver        1.4.4
MarkupSafe        2.1.3
matplotlib        3.7.1
matplotlib-inline 0.1.6
nest-asyncio      1.5.6
numpy             1.25.0
openpyxl          3.1.2
packaging         23.1
pandas            2.0.2
parso             0.8.3
pickleshare       0.7.5
Pillow            9.5.0
pip               23.1.2
platformdirs      3.7.0
prompt-toolkit    3.0.38
psutil            5.9.5
pure-eval         0.2.2
Pygments          2.15.1
PyMySQL           1.0.3
pyparsing         3.1.0
python-dateutil   2.8.2
py

In [2]:
!pip install numpy

In [3]:
!pip install pandas

In [4]:
#import
import pandas as pd
import numpy as np

##### numpy를 쓰는 이유
- pytonh 리스트를 만들고 사용처리(1,000,000건) -260ms
- numpy 배열을 만들고 처리하는데(1,000,000건) - 34.3ms(8배정도 빠름)

In [6]:
py_list = list(range(1_000_000)) # 100만건 리스트 만들기

In [7]:
np_arr = np.arange(1_000_000)

In [8]:
## 파이썬 리스트 사용
%timeit for _ in range(10): py_list2 = py_list * 2

150 ms ± 661 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
## 넘파이로 리스트 사용
%timeit for _ in range(10): np_arr2 = np_arr * 2

13.6 ms ± 326 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### 넘파이로 배열 생성, 연산 등

- 파이썬 리스트는+(리스트끼리), *(숫자만) 연산 밖에 없음
- 행렬(벡터)로 연산을 하고 싶으면 numpy 배열로 형변환 후에 처리할 것

In [10]:
# 1차원 배열
np_arr1 = np.array([1, 3, 5])
np_arr1

array([1, 3, 5])

In [12]:
# 2차원 배열
np_arr2 = np.array([[1, 3, 5], [5, 9, 12]])
np_arr2

array([[ 1,  3,  5],
       [ 5,  9, 12]])

In [15]:
# 3차원 배열
np_arr3 = np.array([[[0,2,4], [8, 10, 12]],[[1,3,5], [7, 9, 12]]])
np_arr3

array([[[ 0,  2,  4],
        [ 8, 10, 12]],

       [[ 1,  3,  5],
        [ 7,  9, 12]]])

In [16]:
# 파이썬 기본 리스트(배열)
list1 = [1, 3,5]
list1

[1, 3, 5]

In [18]:
# [1, 3, 5], [1, 3, 5]는 튜플로 1차우 ㅓㄴ 배열이 두개 만들어짐 -> numpy에서는 허용안됨
# [[1, 3, 5], [1, 3, 5]] 2차원 배열
list2 = [[1, 3, 5], [1, 3, 5]]
list2

[[1, 3, 5], [1, 3, 5]]

In [19]:
# 길의 4의 1차원 배열을 전부 0으로 채울것
np_arr4 = np.zeros(4)
np_arr4

array([0., 0., 0., 0.])

In [20]:
np_arr5 = np.zeros([2, 3])
np_arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np_arr6 = np.empty((2, 3, 1))
np_arr6

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [23]:
# 랜덤은 활용도 있음
np.random.randn(2 ,3)

array([[ 0.13187414, -0.61478851,  0.90280457],
       [ 1.05824413, -0.70894901, -0.20381397]])

In [27]:
np_arr7 = np.arange(10)
np_arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# 파이썬에서 리스트만든 다음에 numpy형태의 배열로 변경
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 연산
np_arr7 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
list(np_arr7) * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
np_arr7 * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [30]:
np_arr7 / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [31]:
np_arr7 // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [35]:
# numpy 배열은 +더하기 연산
np_arr7 + np_arr7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# 파이썬 리스트 + concat(두 리스트를 합침)
list(range(10)) +list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
# 비교연산
(np_arr7 + np_arr7) < 9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [34]:
(np_arr7 + np_arr7) != 10

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [39]:
# 조회
np_arr7[1]

1

In [40]:
# 인덱스 크기를 벗어나면 IndexError 예외발생
np_arr7[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [41]:
np_arr7[np_arr7 < 5]

array([0, 1, 2, 3, 4])

In [42]:
list2 = list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
[x for x in range(10) if x < 5] # 리스트 내포

[0, 1, 2, 3, 4]

In [44]:
np_arr7[3:9] # 뒤에 인덱스는 항상 -1

array([3, 4, 5, 6, 7, 8])

In [45]:
# 2차원 배열에서 값 조회
np_arr2[1][2]

12

In [46]:
np_arr2[1, 2]

12

In [48]:
# 값 변경(치환)
np_arr7[np_arr7 < 5] = 100
np_arr7

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

##### 속성

- shape, dtype, T

In [49]:
# 1차원
np_arr1.shape

(3,)

In [51]:
# 2차원
np_arr2.shape

(2, 3)

In [53]:
np_arr2.dtype

dtype('int32')

In [54]:
np_arr2.T

array([[ 1,  5],
       [ 3,  9],
       [ 5, 12]])

In [55]:
np_arr2.T.shape

(3, 2)

In [57]:
np_arr8 = np.arange(10)
np_arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np_arr8.mean()

4.5

In [59]:
np_arr8.sum()

45

In [60]:
np_arr8.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [62]:
np_arr9 = np.random.randn(10)
np_arr9

array([-0.06941961,  0.10921215, -0.37128384, -0.73732561,  0.24811028,
       -0.12793397,  0.87931562,  1.02164392,  0.00357423,  0.33455   ])

In [63]:
np_arr9.sort()

In [64]:
np_arr9

array([-0.73732561, -0.37128384, -0.12793397, -0.06941961,  0.00357423,
        0.10921215,  0.24811028,  0.33455   ,  0.87931562,  1.02164392])

In [65]:
# 내림차순 정렬
-np.sort(-np_arr9)

array([ 1.02164392,  0.87931562,  0.33455   ,  0.24811028,  0.10921215,
        0.00357423, -0.06941961, -0.12793397, -0.37128384, -0.73732561])

##### 테스트용 데이터프레임 예제

In [85]:
# 테스트용 더미데이터프레임 만들기
# 판다스와 조합해서 생성
size = 10
df = pd.DataFrame({
    'class' : [['A', 'B', 'C', 'D','F'][np.random.randint(0, 5)] for i in range(0, size)],
    'year' : [np.random.randint(2010, 2024) for i in range(0, size)],
    'month' : [np.random.randint(1, 13) for i in range(0, size)],
    'val1' : [np.random.randint(1, 11) for i in range(0, size)],
    'val2' : [np.random.randint(100, 1000) for i in range(0, size)],
    'val3' : [np.random.randint(10000, 20000) for i in range(0, size)]
})

df

class  year  month  val1  val2   val3
0     B  2013     12    10   505  16409
1     F  2016      4     4   948  13525
2     C  2019     12     5   928  12621
3     B  2017      4     2   732  16566
4     F  2016      4     5   269  16942
5     F  2019      4     4   440  10569
6     A  2019      2     1   781  14970
7     A  2021      1     1   819  19569
8     D  2023      3     6   511  10927
9     F  2012      8     1   815  11405

In [87]:
df.shape

(10, 6)

In [88]:
df.dtypes

class    object
year      int64
month     int64
val1      int64
val2      int64
val3      int64
dtype: object

In [91]:
df.T.shape

(6, 10)

In [92]:
df.T

0      1      2      3      4      5      6      7      8      9
class      B      F      C      B      F      F      A      A      D      F
year    2013   2016   2019   2017   2016   2019   2019   2021   2023   2012
month     12      4     12      4      4      4      2      1      3      8
val1      10      4      5      2      5      4      1      1      6      1
val2     505    948    928    732    269    440    781    819    511    815
val3   16409  13525  12621  16566  16942  10569  14970  19569  10927  11405